### ISSUE TITLE
cf_find_station error when datatype specified

### ISSUE THREAD

**Issue by nevermana-landcare** [ropensci/clifro#30]
I've encountered an error searching for stations when I specify a datatype. When no datatype is specified, the code works fine. The error occurs for both region and latlon searches. 

CliFro v3.2-3

```r
precipDaily.dt = cf_datatype(3,1,1) # Daily precipitation data

kaitaia <- cf_find_station("kaitaia", search = "region", datatype = precipDaily.dt, status = "all")
```

```r
Error: Assigned data `dmy(doc_table$Start, tz = "NZ")` must be compatible with existing data.
x Existing data has 116 rows.
x Assigned data has 0 rows.
ℹ Only vectors of size 1 are recycled.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
Unknown or uninitialised column: `Start`. 
```

**Comment by blasee** [comment]
Hi @nevermana-landcare,

Thanks for submitting a bug report. This error has been fixed in the latest version of *clifro*. You can update *clifro* with the following lines of code.

```r
install.packages("remotes")
remotes::install_github("ropensci/clifro")

# Check package version
packageVersion("clifro") # should be 3.2-5
```

You should then be able to successfully run your code snippet. Please let me know if you run into any other issues :-)

**Comment by sli-leew** [comment]
Hi, I still get the reporter's error, and a similar error with a query I am working with, on clifro 3.2.5

I tried with both the latest CRAN release, and the latest dev version (both report version 3.2.5)

```
> packageVersion("clifro")
[1] ‘3.2.5’

> library(clifro)
> public.cfuser = cf_user()
> combined.dt = cf_datatype(1, 2, 2, 1)
> stations.st = cf_find_station(lat=-43.5320, long=172.6306, search="latlong", status="open", rad=25, datatype=combined.dt)
Error: Assigned data `dmy(doc_table$Start, tz = "NZ")` must be compatible with existing data.
x Existing data has 8 rows.
x Assigned data has 0 rows.
i Only vectors of size 1 are recycled.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
Unknown or uninitialised column: `Start`. 


> precipDaily.dt = cf_datatype(3,1,1) # Daily precipitation data
> 
> kaitaia <- cf_find_station("kaitaia", search = "region", datatype = precipDaily.dt, status = "all")
Error: Assigned data `dmy(doc_table$Start, tz = "NZ")` must be compatible with existing data.
x Existing data has 116 rows.
x Assigned data has 0 rows.
i Only vectors of size 1 are recycled.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
Unknown or uninitialised column: `Start`. 
```

**Comment by blasee** [comment]
Hi @sli-leew,

I can't seem to reproduce the error. Your code works for me on both my windows and linux machines:

```r
> public.cfuser = cf_user()
> combined.dt = cf_datatype(1, 2, 2, 1)
> stations.st = cf_find_station(lat=-43.5320, long=172.6306, search="latlong", status="open", rad=25, datatype=combined.dt)
> stations.st
                           name network agent      start        end open distance       lat      lon
1)                 Rangiora Ews  H32364 17244 1999-02-18 2021-06-24 TRUE     22.6 -43.32858 172.6111
2)      Lincoln, Broadfield Ews  H32645 17603 1999-07-01 2021-06-24 TRUE     16.6 -43.62622 172.4704
3)    Christchurch, Kyle St Ews  H3256F 24120 2002-11-01 2021-06-24 TRUE      1.8 -43.53074 172.6077
4)          Diamond Harbour Ews  H32674 40985 2015-09-18 2021-06-24 TRUE     13.7 -43.63312 172.7281
5)                    Ohoka Cws  H32359 43251 2017-09-23 2021-06-24 TRUE     21.7 -43.34230 172.5657
6)                  Bromley Ews  H3257J 43967 2019-12-20 2021-06-24 TRUE      7.3 -43.52828 172.7210
7)            Christchurch Aero  H32451  4843 2009-06-30 2021-06-23 TRUE      8.7 -43.49300 172.5370
8) Christchurch Aero Backup Aws  H32455 41230 2013-08-15 2021-06-23 TRUE      9.5 -43.48901 172.5284
```

```r
> precipDaily.dt = cf_datatype(3,1,1) # Daily precipitation data
> kaitaia <- cf_find_station("kaitaia", search = "region", datatype = precipDaily.dt, status = "all")
> kaitaia
                               name network agent      start        end  open distance       lat      lon
1)                     Kerikeri Ews  A53191  1056 1981-10-01 2021-06-24  TRUE       NA -35.18300 173.9260
2)                  Cape Reinga Aws  A42462  1002 1983-08-23 2021-06-24  TRUE       NA -34.42963 172.6819
3)                      Purerua Aws  A54101  1196 1983-10-07 2021-06-24  TRUE       NA -35.12900 174.0150
4)                      Kaikohe Aws  A53487  1134 1985-12-01 2021-06-24  TRUE       NA -35.41720 173.8229
...
```

Can you please paste the output of `sessionInfo()`:

```r
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] clifro_3.2-5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         rstudioapi_0.13    xml2_1.3.2         magrittr_2.0.1     rvest_0.3.6        tidyselect_1.1.0   munsell_0.5.0      colorspace_2.0-0   R6_2.5.0           rlang_0.4.10       stringr_1.4.0     
[12] plyr_1.8.6         httr_1.4.2         dplyr_1.0.3        tools_4.0.3        grid_4.0.3         gtable_0.3.0       selectr_0.4-2      ellipsis_0.3.1     tibble_3.0.5       lifecycle_0.2.0    crayon_1.3.4      
[23] purrr_0.3.4        RColorBrewer_1.1-2 reshape2_1.4.4     ggplot2_3.3.3      vctrs_0.3.6        curl_4.3           glue_1.4.2         stringi_1.6.2      compiler_4.0.3     pillar_1.4.7       generics_0.1.0    
[34] scales_1.1.1       lubridate_1.7.9.2  pkgconfig_2.0.3   
```

**Comment by blasee** [comment]
Hi @sli-leew,

Thanks for reporting this. I can confirm that I can reproduce this error. The latest development version should have resolved this bug:

```r
install.packages("remotes")
remotes::install_github("ropensci/clifro")
library(clifro) 
packageVersion("clifro") # 3.2.5.9000

public.cfuser = cf_user()
combined.dt = cf_datatype(1, 2, 2, 1)
stations.st = cf_find_station(lat=-43.5320, long=172.6306, search="latlong", status="open", rad=25, datatype=combined.dt)

> stations.st
                           name network agent      start        end open distance       lat      lon
1)                 Rangiora Ews  H32364 17244 1999-02-18 2021-06-24 TRUE     22.6 -43.32858 172.6111
2)      Lincoln, Broadfield Ews  H32645 17603 1999-07-01 2021-06-24 TRUE     16.6 -43.62622 172.4704
3)    Christchurch, Kyle St Ews  H3256F 24120 2002-11-01 2021-06-24 TRUE      1.8 -43.53074 172.6077
4)          Diamond Harbour Ews  H32674 40985 2015-09-18 2021-06-24 TRUE     13.7 -43.63312 172.7281
5)                    Ohoka Cws  H32359 43251 2017-09-23 2021-06-24 TRUE     21.7 -43.34230 172.5657
6)                  Bromley Ews  H3257J 43967 2019-12-20 2021-06-24 TRUE      7.3 -43.52828 172.7210
7)            Christchurch Aero  H32451  4843 2009-06-30 2021-06-23 TRUE      8.7 -43.49300 172.5370
8) Christchurch Aero Backup Aws  H32455 41230 2013-08-15 2021-06-23 TRUE      9.5 -43.48901 172.5284
```

Please let me know if you have any other issues.

**Comment by nevermana-landcare** [comment]
Hi @blasee,

I can confirm clifro 3.2.5.900 has resolved the error with my code. Thanks for your prompt response.
